### ISSUE TITLE
[Feature Request] Auto change plank themes

### ISSUE THREAD

**Issue by matfantinel** [maze-n/indicator-daynight#8]
[This script](https://github.com/veyselerden/elementaryos-dark-theme-enabler-script/blob/master/enable-dark-theme.sh) has some lines that basically swap the `dock.theme` and `dock-dark.theme`  in `/usr/share/themes/elementary/plank` folder.

Would be great if this could do that too! I'm not sure if it's doable as it may require root access, but it's worth a shot?

**Comment by maze-n** [comment]
I'm sorry but I don't think I can use that script as a way to switch Plank theme, since, like you said yourself it is only copying the dock theme file and replacing it with another theme file for dark theme (**and also in root directory too!!**).

Anyways let's keep this issue open for anyone in the future to implement this feature in a proper way...

**Comment by matfantinel** [comment]
This is gonna be implemented on elementaryOS 6, so I'm closing this issue.
